
import type { MenuItem } from './types';

export const menuData: MenuItem[] = [
  {
    id: '1',
    name: 'Classic Cheeseburger',
    description: 'A juicy beef patty with melted cheddar cheese, lettuce, tomato, and our special sauce.',
    price: 90,
    image: 'https://placehold.co/600x400.png',
    category: 'Burgers',
  },
  {
    id: '2',
    name: 'Bacon Avocado Burger',
    description: 'The classic, but with crispy bacon and fresh avocado slices. A fan favorite!',
    price: 120,
    image: 'https://placehold.co/600x400.png',
    category: 'Burgers',
  },
  {
    id: '9',
    name: 'Spicy Jalapeno Burger',
    description: 'A fiery beef patty with pepper jack cheese, spicy jalapenos, and a chipotle aioli.',
    price: 110,
    image: 'https://placehold.co/600x400.png',
    category: 'Burgers',
  },
  {
    id: '3',
    name: 'Margherita Pizza',
    description: 'Simple yet delicious, with fresh mozzarella, San Marzano tomatoes, and basil.',
    price: 140,
    image: 'https://placehold.co/600x400.png',
    category: 'Pizzas',
  },
  {
    id: '4',
    name: 'Pepperoni Pizza',
    description: 'A timeless classic covered in high-quality pepperoni and melted mozzarella cheese.',
    price: 160,
    image: 'https://placehold.co/600x400.png',
    category: 'Pizzas',
  },
  {
    id: '10',
    name: 'Veggie Supreme Pizza',
    description: 'A delicious mix of bell peppers, onions, olives, mushrooms, and mozzarella cheese.',
    price: 170,
    image: 'https://placehold.co/600x400.png',
    category: 'Pizzas',
  },
  {
    id: '5',
    name: 'Crispy French Fries',
    description: 'Golden, crispy, and lightly salted. The perfect companion to any meal.',
    price: 40,
    image: 'https://placehold.co/600x400.png',
    category: 'Sides',
  },
  {
    id: '6',
    name: 'Onion Rings',
    description: 'Thick-cut onion rings, beer-battered and fried to a perfect golden brown.',
    price: 50,
    image: 'https://placehold.co/600x400.png',
    category: 'Sides',
  },
  {
    id: '11',
    name: 'Mozzarella Sticks',
    description: 'Crispy on the outside, gooey on the inside. Served with marinara sauce.',
    price: 60,
    image: 'https://placehold.co/600x400.png',
    category: 'Sides',
  },
  {
    id: '7',
    name: 'Fountain Soda',
    description: 'Choose from a variety of refreshing Coca-Cola products.',
    price: 20,
    image: 'https://placehold.co/600x400.png',
    category: 'Drinks',
  },
  {
    id: '8',
    name: 'Craft Lemonade',
    description: 'Freshly squeezed lemons with a hint of mint. Sweet and tangy.',
    price: 30,
    image: 'https://placehold.co/600x400.png',
    category: 'Drinks',
  },
  {
    id: '12',
    name: 'Iced Tea',
    description: 'Freshly brewed iced tea, served unsweetened or sweetened.',
    price: 30,
    image: 'https://placehold.co/600x400.png',
    category: 'Drinks',
  },
];
